language: c
os: osx
osx_image: xcode7.3

cache:
  directories:
  - node_modules
  - $HOME/.electron
  - $HOME/.cache

before_install:
  - mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v1.5.5/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-1.5.5.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
- nvm install 8
- yarn add electron-builder@next --dev # force install next version to test electron-builder
- yarn install

script:
- yarn run build-assets
- yarn run dist

branches:
  only:
    - master
    - /^dev-.*$/
