version: 0.4.{build}

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - yarn add electron-builder@next --dev # force install next version to test electron-builder
  - yarn install

build_script:
  - yarn run build-assets
  - yarn run dist

test: off

branches:
  only:
    - master
    - /^dev-.*$/
